- name: Ensure "opt" sub directory exists
  file:
    path: "/opt/{{ dns_name }}"
    state: directory
    mode: 0700

- name: Copy "requirements.txt" file
  copy:
    src: requirements.txt
    dest: /opt/{{ dns_name }}/requirements.txt
    mode: 0600

- name: Copy "wsgi.py" file
  copy:
    src: wsgi.py
    dest: /opt/{{ dns_name }}/wsgi.py
    mode: 0600

- name: Copy "templates" file
  copy:
    src: templates
    dest: /opt/{{ dns_name }}
    mode: 0600

- name: Copy "docker-compose.yml" file
  copy:
    src: docker-compose.yml
    dest: /opt/{{ dns_name }}/docker-compose.yml
    mode: 0600

- name: Copy "docker-compose.prod.yml" file
  copy:
    src: docker-compose.prod.yml
    dest: /opt/{{ dns_name }}/docker-compose.prod.yml
    mode: 0600

- name: Copy "Dockerfile" file
  copy:
    src: Dockerfile
    dest: /opt/{{ dns_name }}/Dockerfile
    mode: 0600

- name: Copy "bankaccounts" file
  synchronize:
      src: bankaccounts
      dest: /opt/{{ dns_name }}
